import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Share } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { format, parseISO } from 'date-fns';
import Toast from 'react-native-toast-message';
import { useTheme } from '../context/ThemeContext';
import { colors, spacing, radius } from '../theme/colors';
import { mockPets, mockVaccinations } from '../data/mockData';

export default function HealthReportScreen({ route, navigation }: any) {
  const { petId } = route.params || {};
  const { colors: tc, isDark } = useTheme();
  const s = styles(tc, isDark);
  const pet = mockPets.find(p => p.id === petId) || mockPets[0];
  const vacs = mockVaccinations.filter(v => v.petId === petId);

  const shareReport = async () => {
    try {
      await Share.share({
        title: `${pet.name}'s Health Report`,
        message: `PetWatch Health Report for ${pet.name}\n\nSpecies: ${pet.species}\nBreed: ${pet.breed}\nAge: ${pet.age} years\nWeight: ${pet.weight} kg\n\nVaccinations: ${vacs.length} records on file\n\nGenerated by PetWatch on ${format(new Date(), 'MMMM dd, yyyy')}`,
      });
    } catch (e) {
      Toast.show({ type: 'error', text1: 'Could not share report' });
    }
  };

  const sendToVet = () => {
    Toast.show({ type: 'success', text1: 'Report sent to your vet!', text2: 'They will review it shortly.' });
  };

  const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
    <View style={s.section}>
      <Text style={s.sectionTitle}>{title}</Text>
      {children}
    </View>
  );

  const Row = ({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) => (
    <View style={s.row}>
      <Text style={s.rowLabel}>{label}</Text>
      <Text style={[s.rowValue, highlight && { color: colors.primary, fontWeight: '600' }]}>{value}</Text>
    </View>
  );

  const overallStatus = vacs.length > 0 ? 'Good' : 'Needs Attention';

  return (
    <SafeAreaView style={s.safe}>
      <View style={s.nav}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={s.backBtn}><Ionicons name="arrow-back" size={22} color={tc.text} /></TouchableOpacity>
        <Text style={s.navTitle}>Health Report</Text>
        <TouchableOpacity style={s.shareBtn} onPress={shareReport}><Ionicons name="share-outline" size={22} color={colors.primary} /></TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={s.container}>
        <View style={s.reportHeader}>
          <View style={[s.petAvatar, { backgroundColor: isDark ? '#1e3a5f' : '#EFF6FF' }]}>
            <Ionicons name="paw" size={36} color={colors.primary} />
          </View>
          <Text style={s.petName}>{pet.name}</Text>
          <Text style={s.petBreed}>{pet.breed}</Text>
          <View style={[s.statusChip, { backgroundColor: '#F0FDF4', borderColor: '#BBF7D0' }]}>
            <Ionicons name="checkmark-circle" size={14} color={colors.success} />
            <Text style={[s.statusText, { color: '#166534' }]}>{overallStatus}</Text>
          </View>
          <Text style={s.reportDate}>Report generated {format(new Date(), 'MMMM dd, yyyy')}</Text>
        </View>

        <Section title="Basic Information">
          <Row label="Species" value={pet.species} />
          <Row label="Breed" value={pet.breed} />
          <Row label="Age" value={`${pet.age} years`} />
          <Row label="Weight" value={`${pet.weight} kg`} />
          <Row label="Color" value={pet.color || 'N/A'} />
        </Section>

        <Section title="Vaccination Summary">
          <Row label="Total Records" value={`${vacs.length}`} highlight />
          {vacs.map(v => (
            <View key={v.id} style={s.vacRow}>
              <Ionicons name="medical" size={14} color={colors.primary} />
              <View style={{ flex: 1, marginLeft: 8 }}>
                <Text style={s.vacName}>{v.vaccine}</Text>
                <Text style={s.vacDate}>Administered: {format(parseISO(v.date), 'MMM dd, yyyy')} · Next: {format(parseISO(v.nextDue), 'MMM dd, yyyy')}</Text>
              </View>
            </View>
          ))}
          {vacs.length === 0 && <Text style={s.noData}>No vaccination records</Text>}
        </Section>

        <Section title="Deworming">
          <Row label="Last Deworming" value={pet.lastDewormingDate ? format(parseISO(pet.lastDewormingDate), 'MMM dd, yyyy') : 'Not recorded'} />
          <Row label="Next Due" value={pet.nextDewormingDate ? format(parseISO(pet.nextDewormingDate), 'MMM dd, yyyy') : 'Not scheduled'} highlight />
        </Section>

        <Section title="Recent Symptom Reports">
          <Text style={s.noData}>No recent symptom reports</Text>
        </Section>

        <View style={s.actionRow}>
          <TouchableOpacity style={s.outlineBtn} onPress={shareReport}>
            <Ionicons name="share-outline" size={16} color={tc.text} />
            <Text style={s.outlineBtnText}>Share PDF</Text>
          </TouchableOpacity>
          <TouchableOpacity style={s.primaryBtn} onPress={sendToVet}>
            <Ionicons name="send" size={16} color="#fff" />
            <Text style={s.primaryBtnText}>Send to Vet</Text>
          </TouchableOpacity>
        </View>

        <View style={s.footer}>
          <Text style={s.footerText}>This report is generated by PetWatch and should not replace professional veterinary advice.</Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = (tc: any, isDark: boolean) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: tc.background },
  nav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.md, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: tc.border },
  backBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  navTitle: { fontSize: 17, fontWeight: '600', color: tc.text },
  shareBtn: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  container: { padding: spacing.md, paddingBottom: 40 },
  reportHeader: { alignItems: 'center', backgroundColor: tc.surface, borderRadius: radius.lg, padding: 24, marginBottom: 16, borderWidth: 1, borderColor: tc.border },
  petAvatar: { width: 80, height: 80, borderRadius: 40, alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  petName: { fontSize: 22, fontWeight: '700', color: tc.text },
  petBreed: { fontSize: 14, color: tc.textSecondary, marginTop: 2, marginBottom: 10 },
  statusChip: { flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1, borderRadius: radius.full, paddingHorizontal: 12, paddingVertical: 6, marginBottom: 8 },
  statusText: { fontSize: 13, fontWeight: '600' },
  reportDate: { fontSize: 12, color: tc.textMuted },
  section: { backgroundColor: tc.surface, borderRadius: radius.lg, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: tc.border },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: tc.text, marginBottom: 12, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: tc.border },
  row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: tc.border },
  rowLabel: { fontSize: 14, color: tc.textSecondary },
  rowValue: { fontSize: 14, color: tc.text },
  vacRow: { flexDirection: 'row', alignItems: 'flex-start', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: tc.border },
  vacName: { fontSize: 14, fontWeight: '600', color: tc.text },
  vacDate: { fontSize: 12, color: tc.textSecondary, marginTop: 2 },
  noData: { fontSize: 13, color: tc.textMuted, fontStyle: 'italic', paddingVertical: 8 },
  actionRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  outlineBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, borderWidth: 1, borderColor: tc.border, borderRadius: radius.md, paddingVertical: 13 },
  outlineBtnText: { fontSize: 14, color: tc.text, fontWeight: '500' },
  primaryBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: colors.primary, borderRadius: radius.md, paddingVertical: 13 },
  primaryBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  footer: { alignItems: 'center', padding: 16 },
  footerText: { fontSize: 12, color: tc.textMuted, textAlign: 'center', lineHeight: 18 },
});
