const TONE_COLORS = {
  good: { dot: '#0ca982', text: '#087e70' },
  attention: { dot: '#df8a00', text: '#965700' },
  urgent: { dot: '#e42d27', text: '#c51f18' },
  progress: { dot: '#3674e8', text: '#1d55bd' },
  inactive: { dot: '#9aa9a5', text: '#526663' },
};

const STATUS_TONES = {
  confirmed: 'good',
  active: 'good',
  available: 'good',
  paid: 'good',
  success: 'good',
  finalized: 'good',
  normal: 'good',
  healthy: 'good',
  'healthy stock': 'good',
  'in stock': 'good',
  received: 'good',
  delivered: 'good',
  approved: 'good',
  verified: 'good',
  'up to date': 'good',
  fresh: 'good',
  pending: 'attention',
  waiting: 'attention',
  draft: 'attention',
  issued: 'attention',
  'due soon': 'attention',
  'low stock': 'attention',
  'reorder soon': 'attention',
  'expiring soon': 'attention',
  'needs review': 'attention',
  'waiting on reception': 'attention',
  moderate: 'attention',
  watch: 'attention',
  busy: 'attention',
  'on duty': 'good',
  overdue: 'urgent',
  abnormal: 'urgent',
  critical: 'urgent',
  'critical stock': 'urgent',
  'out of stock': 'urgent',
  failed: 'urgent',
  error: 'urgent',
  rejected: 'urgent',
  duplicated: 'urgent',
  cancelled: 'inactive',
  canceled: 'inactive',
  completed: 'inactive',
  discharged: 'inactive',
  'checked out': 'inactive',
  paused: 'inactive',
  inactive: 'inactive',
  archived: 'inactive',
  'no show': 'inactive',
  'no-show': 'inactive',
  'checked in': 'progress',
  'in consultation': 'progress',
  admitted: 'progress',
  'in progress': 'progress',
  'in transit': 'progress',
  rescheduled: 'progress',
  scheduled: 'progress',
  booked: 'progress',
  due: 'progress',
  'reschedule request': 'progress',
  'cancel request': 'attention',
  open: 'progress',
  resolved: 'inactive',
  stale: 'attention',
  outdated: 'urgent',
  'high risk': 'urgent',
  stable: 'good',
  low: 'good',
};

function normalizeStatus(status) {
  return String(status || '').trim().toLowerCase().replace(/[_-]+/g, ' ').replace(/\s+/g, ' ');
}

export function getStatusToneColors(status) {
  return TONE_COLORS[STATUS_TONES[normalizeStatus(status)] || 'inactive'];
}
